### ISSUE TITLE
Theme内の画像のライセンスを明記した方が良いと思います。

### ISSUE THREAD

**Issue by shimakyohsuke** [s56bouya/nishiki#19]
以下、画像のライセンスを明記した方がいいと思います。
<https://github.com/s56bouya/nishiki/blob/master/images/carp.jpg>

参考：
<https://github.com/wckansai2016/for-the-future/blob/master/readme.txt#L49>

**Comment by s56bouya** [comment]
ありがとうございます！時期バージョンアップで対応させていただきます。

**Comment by s56bouya** [comment]
スクリーンショットと鯉画像のライセンスを明記しました！

https://github.com/s56bouya/nishiki/blob/master/readme.txt#L38-L39

こちらで一旦クローズしますね。どうもありがとうございました！
